#!/usr/bin/env python3
"""Generate docs/PRESET_CATALOG.md from controllers/*.json and docs/device_notes/."""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CONTROLLERS_DIR = REPO_ROOT / "controllers"
NOTES_DIR = REPO_ROOT / "docs" / "device_notes"
OUT_PATH = REPO_ROOT / "docs" / "PRESET_CATALOG.md"

CATEGORY_ORDER = [
    "graphics_cards",
    "motherboard",
    "cpu_cooler",
    "fans",
    "keyboards",
    "mouses",
    "mousemats",
    "speakers",
    "headsets",
    "led_strips",
    "cases",
    "accessories",
    "uncategorized",
]

CATEGORY_TITLES = {
    "graphics_cards": "Graphics Cards",
    "motherboard": "Motherboards",
    "cpu_cooler": "CPU Coolers",
    "fans": "Fans",
    "keyboards": "Keyboards",
    "mouses": "Mice",
    "mousemats": "Mousemats",
    "speakers": "Speakers",
    "headsets": "Headsets",
    "led_strips": "LED Strips",
    "cases": "Cases",
    "accessories": "Accessories",
    "uncategorized": "Uncategorized",
}

NOTE_META_RE = re.compile(
    r"<!--\s*catalog\s*\n(.*?)\n\s*-->",
    re.DOTALL | re.IGNORECASE,
)


def category_title(slug: str) -> str:
    if slug in CATEGORY_TITLES:
        return CATEGORY_TITLES[slug]
    return slug.replace("_", " ").title()


def category_sort_key(slug: str) -> tuple[int, str]:
    try:
        return (CATEGORY_ORDER.index(slug), slug)
    except ValueError:
        return (len(CATEGORY_ORDER), slug)


def load_presets() -> list[dict]:
    presets: list[dict] = []
    for path in sorted(CONTROLLERS_DIR.rglob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        presets.append(
            {
                "file": path.name,
                "rel": path.relative_to(CONTROLLERS_DIR).as_posix(),
                "stem": path.stem,
                "name": str(data.get("name") or path.stem),
                "brand": str(data.get("brand") or "").strip() or "—",
                "model": str(data.get("model") or "").strip() or "—",
                "category": str(data.get("category") or "").strip() or "uncategorized",
            }
        )
    return presets


def parse_note(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    match = NOTE_META_RE.search(text)
    if not match:
        return None

    title = path.stem.replace("_", " ").title()
    prefixes: list[str] = []
    for line in match.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip().lower()
        value = value.strip()
        if key == "title":
            title = value
        elif key == "prefixes":
            prefixes = [p.strip() for p in value.split(",") if p.strip()]

    if not prefixes:
        prefixes = [path.stem + "_", path.stem]

    body = NOTE_META_RE.sub("", text, count=1).strip()
    return {"path": path, "title": title, "prefixes": prefixes, "body": body}


def load_notes() -> list[dict]:
    if not NOTES_DIR.is_dir():
        return []
    notes: list[dict] = []
    for path in sorted(NOTES_DIR.glob("*.md")):
        note = parse_note(path)
        if note:
            notes.append(note)
    return notes


def note_matches(note: dict, stems: set[str]) -> bool:
    for stem in stems:
        for prefix in note["prefixes"]:
            if stem == prefix.rstrip("_") or stem.startswith(prefix):
                return True
    return False


def md_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def build_catalog(presets: list[dict], notes: list[dict]) -> str:
    by_category: dict[str, list[dict]] = defaultdict(list)
    for preset in presets:
        by_category[preset["category"]].append(preset)

    lines = [
        "<!-- Generated by scripts/generate_preset_catalog.py — do not edit by hand. -->",
        "",
        "# Available presets",
        "",
        "Browse controller layout presets by category. Install by copying files from "
        "[`controllers/`](../controllers/) into your OpenRGB plugin settings folder "
        "(see the [README](../README.md#how-to-install)).",
        "",
        f"**{len(presets)}** preset(s) in this repository.",
        "",
    ]

    for category in sorted(by_category.keys(), key=category_sort_key):
        rows = sorted(
            by_category[category],
            key=lambda p: (p["brand"].lower(), p["model"].lower(), p["name"].lower()),
        )
        lines.append(f"## {category_title(category)}")
        lines.append("")
        lines.append("| Brand | Model | Layout | File |")
        lines.append("| ----- | ----- | ------ | ---- |")
        for row in rows:
            file_link = f"[`{row['rel']}`](../controllers/{row['rel']})"
            lines.append(
                f"| {md_cell(row['brand'])} | {md_cell(row['model'])} | "
                f"{md_cell(row['name'])} | {file_link} |"
            )
        lines.append("")

        stems = {row["stem"] for row in rows}
        for note in notes:
            if note_matches(note, stems):
                lines.append(f"### {note['title']}")
                lines.append("")
                lines.append(note["body"])
                lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Regenerate after changing presets or device notes: "
        "`python scripts/generate_preset_catalog.py`"
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    presets = load_presets()
    if not presets:
        raise SystemExit(f"No presets found in {CONTROLLERS_DIR}")

    notes = load_notes()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(build_catalog(presets, notes), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)} ({len(presets)} presets, {len(notes)} notes)")


if __name__ == "__main__":
    main()
